service: cars-rest-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  app:
    handler: handler.app
    events:
      - http: any {proxy+}

resources:
  Resources:
    usersTables:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            keyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnites: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
